BEGIN;

DROP TABLE IF EXISTS "agent",
"role",
"skill",
"weapon",
"type",
"agent_has_weapon";


CREATE TABLE "role" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);
CREATE TABLE "agent" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "quote" text,
    "role_id" integer NOT NULL REFERENCES "role"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "skill" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "agent_id" integer NOT NULL REFERENCES "agent"("id"),
    "description" text,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "type" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "weapon" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "price" integer NOT NULL,
    "type_id" integer NOT NULL REFERENCES "type"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "agent_has_weapon" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "agent_id" integer NOT NULL REFERENCES "agent"("id") ON DELETE CASCADE,
    "weapon_id" integer NOT NULL REFERENCES "weapon"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
    UNIQUE ("agent_id", "weapon_id")
);


COMMIT;